### Requires "REST Client" in Visual Studio Code
### This allows a simple test right out of VSC.
### Adust the IP adresses below. Run kubectl get svc to figure out the public IPs of your services.
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client


### Call DAPR-enabled endpoint in cluster (frontendapp-a)
###
### -->A-->C-->function
http://20.86.223.211/


### Call endpoint without DAPR (fe-no-dapr)
###
### -->A_nodapr-->C-->function
http://20.101.198.227/

### Call endpoint backendapp-c
###
### -->C-->function
http://20.101.198.158/

### Call your external service
### This could be any http endpoint (even google.com)
### Just make sure this endpoint is configured in the backendapp-C as targeturl
###
### -->function
http://dmx-getrandom.azurewebsites.net/api/HttpTriggerCSharp1