apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    timeouts:
      general: 1s   
    retries:      
      retryXtimes:
        policy: constant
        duration: 200ms
        maxRetries: 5    
  targets:
    apps:
      backendapp-b:
        retry: retryXtimes
   