apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    timeouts:
      general: 1s   
    retries:      
      retry100times:
        policy: constant
        duration: 200ms
        maxRetries: 100    
  targets:
    apps:
      backendapp-c:
        retry: retry100times
   